---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make grafana directory.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ volumes_root }}/grafana"
    - "{{ volumes_root }}/grafana/data"
    - "{{ volumes_root }}/grafana/dashboards"
    - "{{ volumes_root }}/grafana/datasources"

- name: Configure grafana influx datasource
  template:
    src: grafana.datasource.influxdb.yaml
    dest: "{{ volumes_root }}/grafana/datasources/"

- name: Configure grafana influx dashboard
  template:
    src: "{{item}}"
    dest: "{{ volumes_root }}/grafana/dashboards/"
  loop:
    - grafana.dashboards.yaml
    - grafana.dash.homelab.json

- name: Start {{service_item}}
  include: includes/start.yml
