---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Copy grownetics .env file into place.
  template:
    src: env.j2
    dest: "{{ volumes_root }}/grownetics/.env"

- name: Copy telegraf.conf file into place.
  template:
    src: telegraf.conf
    dest: "{{ volumes_root }}/grownetics/telegraf.conf"

- name: Start {{service_item}}
  include: includes/start.yml
