---
- name: Make nzbhydra2 directory.
  file:
    path: "{{ volumes_root }}/nzbhydra2"
    state: directory

- name: Copy nzbhydra2 docker-compose.yml file into place.
  template:
    src: docker-compose.nzbhydra2.yml.j2
    dest: "{{ volumes_root }}/nzbhydra2/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure nzbhydra2 systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/nzbhydra2.service

- name: Start nzbhydra2
  systemd:
    name: nzbhydra2
    enabled: "yes"
    daemon-reload: "yes"
    state: started
