---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Check for existence of httpd.conf
  stat:
    path: "{{ volumes_root }}/apache2/httpd.conf"
  register: httpd_conf_file

- name: Copy default apache config from docker image
  shell:
    cmd: "docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > {{ volumes_root }}/apache2/httpd.conf"
  when: not httpd_conf_file.stat.exists

- name: Start {{service_item}}
  include: includes/start.yml
