---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Copy tiddlywiki.info file into place.
  template:
    src: tiddlywiki.info
    dest: "{{ volumes_root }}/tiddlywiki/tiddlywiki.info"

- name: Start {{service_item}}
  include: includes/start.yml
