---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make sui's config directory
  file:
    path: "{{ volumes_root }}/sui/configs"
    state: directory
    mode: u+rwx,g+rwx,o+rx

- name: Copy sui config files into place.
  template:
    src: "{{ item }}"
    dest: "{{ volumes_root }}/sui/configs/{{ item }}"
  with_items:
    - config.json
    - HomelabOS.json
    - local-docker.json

- name: Start {{service_item}}
  include: includes/start.yml
