---
- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Start {{service_item}}
  include: includes/start.yml

- name: Capture initial password
  shell: >
    docker-compose -f {{ volumes_root }}/peertube/docker-compose.yml logs app | grep -A1 root
  register: peertube_pass
  become: false

- local_action:
    copy content={{ peertube_pass.stdout }}
    dest=./settings/passwords/peertube_root_password

- debug:
    msg: "Peertube credentials: {{peertube_pass.stdout}}"
