---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Copy pixelfed .env file into place.
  template:
    src: pixelfed.env.j2
    dest: "{{ volumes_root }}/pixelfed/pixelfed.env"

- name: Start {{service_item}}
  include: includes/start.yml
