---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Clone invidious repository
  git:
    repo: "https://github.com/iv-org/invidious.git"
    dest: "{{ volumes_root }}/invidious/repo"

- name: Start {{service_item}}
  include: includes/start.yml
