---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Check if userdb.yml exists.
  stat:
    path: "{{ volumes_root }}/authelia/userdb.yml"
  register: userdb

- name: Generate new argon2id compatible password.
  shell: >
    docker run --rm authelia/authelia:latest authelia hash-password {{default_password}} | awk '{print $3}'
  register: authelia_hash
  become: false
  when: not userdb.stat.exists

- name: Copy userdb.yml file into place.
  template:
    src: userdb.yml.j2
    dest: "{{ volumes_root }}/authelia/userdb.yml"
  vars:
    authelia_hash: "{{ authelia_hash.stdout }}"
  when: not userdb.stat.exists

- name: Copy authelia_config.yml file into place.
  template:
    src: authelia_config.yml.j2
    dest: "{{ volumes_root }}/authelia/authelia_config.yml"
  vars:
    domain_parts: "{{ domain.split('.') }}"

- name: Copy authelia_config-tor.yml file into place.
  template:
    src: authelia_config-tor.yml.j2
    dest: "{{ volumes_root }}/authelia/authelia_config-tor.yml"
  vars:
    domain_parts: "{{ domain.split('.') }}"

- name: Start {{service_item}}
  include: includes/start.yml
