---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make config directories
  file:
    path: "{{ volumes_root }}/invoiceninja/config/{{item}}"
    state: directory
  loop:
    - nginx/conf.d
    - php

- name: Make invoiceninja directories
  file:
    path: "{{ volumes_root }}/invoiceninja/{{item}}"
    state: directory
    owner: "{{homelab_ssh_user}}"
    group: "{{homelab_ssh_user}}"
  loop:
    - "public"
    - "logo"
    - "storage"

- name: install nginx config
  template:
    src: nginx.conf
    dest: "{{  volumes_root }}/invoiceninja/config/nginx/nginx.conf"

- name: install PHP config files
  template:
    src: php-cli.j2
    dest: "{{ volumes_root }}/invoiceninja/config/php/{{item}}"
  loop:
    - php-cli.ini
    - php.ini

- name: Generate new encryption key.
  shell: >
    docker run --rm -i invoiceninja/invoiceninja:{{invoiceninja.version}} php artisan key:generate --show |
    awk 'END{print}'
  register: application_key
  become: false

- name: Start {{service_item}}
  include: includes/start.yml
