---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make jenkins home directory.
  file:
    path: "{{ volumes_root }}/jenkins/jenkins_home"
    state: directory
    mode: '777'

- name: Copy jenkins Dockerfile file into place.
  template:
    src: Dockerfile.j2
    dest: "{{ volumes_root }}/jenkins/Dockerfile"

- name: Start {{service_item}}
  include: includes/start.yml
