---
- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make privatebin data directory with correct permissions.
  file:
    path: "{{ volumes_root }}/privatebin/data"
    state: directory
    owner: 65534
    group: 82

- name: Make privatebin conf directory with correct permissions.
  file:
    path: "{{ volumes_root }}/privatebin/cfg"
    state: directory
    owner: 65534
    group: 82

- name: Copy privatebin conf.php file into place if it doesn't exist.
  template:
    src: conf.php.j2
    dest: "{{ volumes_root }}/privatebin/cfg/conf.php"
    force: false

- name: Start {{service_item}}
  include: includes/start.yml
