---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Copy erpnext env file into place.
  template:
    src: env.j2
    dest: "{{ volumes_root }}/erpnext/.env"

- name: Copy erpnext frappe-mariadb.cnf file into place.
  template:
    src: frappe-mariadb.cnf
    dest: "{{ volumes_root }}/erpnext/frappe-mariadb.cnf"

- name: Start {{service_item}}
  include: includes/start.yml
