---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make graylog directories.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ volumes_root }}/graylog"
    - "{{ volumes_root }}/graylog/es_data"
    - "{{ volumes_root }}/graylog/mongo_data"
    - "{{ volumes_root }}/graylog/graylog_journal"
    - "{{ volumes_root }}/graylog/graylog_plugin"

- name: Configure ElasticSearch data directory permissions
  file:
    state: directory
    path: "{{ volumes_root }}/graylog/es_data"
    owner: 1000
    group: 1000
    recurse: yes

- name: Configure MongoDB data directory permissions
  file:
    state: directory
    path: "{{ volumes_root }}/graylog/mongo_data"
    owner: 999
    group: 999
    recurse: yes

- name: Configure Graylog's journal directory permissions
  file:
    state: directory
    path: "{{ volumes_root }}/graylog/graylog_journal"
    owner: 1100
    group: 1100
    recurse: yes

- name: Configure  Graylog's plugin directory permissions
  file:
    state: directory
    path: "{{ volumes_root }}/graylog/graylog_plugin"
    owner: 1100
    group: 1100
    recurse: yes

- name: Start {{service_item}}
  include: includes/start.yml
