---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Copy nginx configuration file into place.
  template:
    src: hubzilla-nginx.conf.j2
    dest: "{{ volumes_root }}/hubzilla/conf/hubzilla-nginx.conf"

- name: Start {{service_item}}
  include: includes/start.yml
