---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make tubearchivist's Redis directory
  file:
    path: "{{ volumes_root }}/tubearchivist/redis"
    state: directory
    mode: u+rwx,g+rwx,o+rx

- name: Make tubearchivist's ElasticSearch directory
  file:
    path: "{{ volumes_root }}/tubearchivist/elasticsearch"
    state: directory
    mode: u+rwx,g+rwx,o+rx

- name: Start {{service_item}}
  include: includes/start.yml