---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Configure pihole systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/pihole.service


- name: Start {{service_item}}
  include: includes/start.yml

- name: Stop systemd-resolve
  systemd:
    name: systemd-resolved
    enabled: "no"
    daemon-reload: "no"
    state: stopped
