---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Check out Turtl server git repo
  git:
    repo: https://github.com/turtl/server.git
    dest: "{{ volumes_root }}/turtl/server"

- name: Start database to create user and empty database. Turtl is not resilient for waiting by itself.
  docker_compose:
    project_src: "{{ volumes_root }}/turtl"
    services:
      - postgres-db
    state: present

- name: Build Turtl project from docker-compose
  docker_compose:
    project_src: "{{ volumes_root }}/turtl"
    build: yes

- name: Start {{service_item}}
  include: includes/start.yml
